const AUTH_ROUTE = {
  ROUTE: 'AUTH_ROUTE',
  LOGIN: 'LOGIN',
};

const UNAUTH_ROUTE = {
  ROUTE: 'UNAUTH_ROUTE',
  SCREEN1: 'SCREEN1',
};

const APP_ROUTE = {
  ROUTE: 'APP_ROUTE',
  DRAWER: 'HOME_DRAWER',
  LIST_CONTACT: 'LIST_CONTACT',
  HISTORY: 'HISTORY',
  INFO_CONTACT: 'INFO_CONTACT',
  EDIT_CONTACT: 'EDIT_CONTACT',
};

export {APP_ROUTE, AUTH_ROUTE, UNAUTH_ROUTE};
